<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Pages;
class PagesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Pages::create([
            'page_title_ar' =>'سياسة الخصوصية',
            'page_title_en' =>'Privacy Policy',
            'page_details_ar' =>' هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق. إذا كنت تحتاج إلى عدد أكبر من الفقرات يتيح لك مولد النص العربى زيادة عدد الفقرات كما تريد، النص لن يبدو مقسما ولا يحوي أخطاء لغوية، مولد النص العربى مفيد لمصممي المواقع على وجه الخصوص، حيث يحتاج العميل فى كثير من الأحيان أن يطلع على صورة حقيقية لتصميم
 الموقع. ومن هنا وجب على المصمم أن يضع نصوصا مؤقتة على التصميم ليظهر للعميل الشكل كاملاً،دور مولد النص العربى أن يوفر على المصمم عناء
  البحث عن نص بديل لا علاقة له بالموضوع الذى يتحدث عنه التصميم فيظهر بشكل لا يليق. هذا النص يمكن أن يتم تركيبه على أي تصميم دون مشكلة فلن يبدو وكأنه نص منسوخ، غير منظم، غير منسق، أو حتى غير مفهوم.
   لأنه مازال نصاً بديلاً ومؤقتاً.',
            'page_details_en' => ' This text is an example of text
that can be replaced in the same space, this text has been generated
from the Arabic text generator, where you can generate such text or many other
texts in addition to increasing the number of characters generated by the application. If you need
a larger number of paragraphs, the Arabic text generator allows you to increase the number of paragraphs as
you want, the text will not appear divided and does not contain linguistic errors, the Arabic text generator
is useful for web designers in particular, as the client often needs to see a real picture For website design. Hence,
the designer must put temporary texts on the design to show the customer the complete form, the role of the Arabic text
generator is to spare the designer the trouble of searching for an alternative text that has nothing to do with the topic
the design is talking about, so it appears in an inappropriate way. This text can be installed on any design without
problem, it will not look like copied text, unorganized, unformatted, or even incomprehensible. Because it is
still an alternate and temporary text. ',

        ]);



        Pages::create([
            'page_title_ar' =>'من نحن',
            'page_title_en' =>'About Us',
            'page_details_ar' =>' يبق أن وجهان مليون التجارية. لكل و بقصف وانتهاءً التبرعات, قد التبرعات ويكيبيديا، أما. تلك جيما عليها جزيرتي ثم, أضف رئيس بتطويق انتصارهم أم. عدم عن فشكّل الأسيوي واعتلاء. لعملة أوروبا إنطلاق عل هذا, عدد مشروط اليابان في. بحث ماشاء طوكيو إذ, بل بأيدي الشرقي دار, بل نقطة أواخر لكل. دنو أن مارد وجهان اوروبا, بها من أسيا مكثّفة سليمان،. ولم كل لمحاكم لبلجيكا،. أم
 سابق الأعمال التكاليف بعض, بها تسبب الشمل الثالث، و.
 يبق أن وجهان مليون التجارية. لكل و بقصف وانتهاءً التبرعات, قد التبرعات ويكيبيديا، أما. تلك جيما عليها جزيرتي ثم, أضف رئيس بتطويق انتصارهم أم. عدم عن فشكّل الأسيوي واعتلاء. لعملة أوروبا إنطلاق عل هذا, عدد مشروط اليابان في. بحث ماشاء طوكيو إذ, بل بأيدي الشرقي دار, بل نقطة أواخر لكل. دنو أن مارد وجهان اوروبا, بها من أسيا مكثّفة سليمان،. ولم كل لمحاكم لبلجيكا،.
 أم سابق الأعمال التكاليف بعض, بها تسبب الشمل الثالث، و.',
            'page_details_en' => ' Lorem Ipsum is simply dummy text of the printing and typesetting industry.
Lorem Ipsum has been the industry&#39;s standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type specimen book.
It has survived not only five centuries, but also the leap into electronic typesetting, remaining
essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,
and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum Lorem Ipsum is
simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#39;s standard
dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
 It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially
  unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and
  more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum Lorem Ipsum
  is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the
  industry&#39;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled
  it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting,
  remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
  Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including
  versions of Lorem Ipsum Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been
  the industry&#39;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled
  it to make a type specimen book. It has survived not only five centuries, but also the leap into
  electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of
  Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker
  including versions of Lorem Ipsum',
        ]);

        Pages::create([
            'page_title_ar' =>'الشروط والأحكام',
            'page_title_en' =>'Terms',
            'page_details_ar' =>' هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق.
 إذا كنت تحتاج إلى عدد أكبر من الفقرات يتيح لك مولد النص العربى زيادة عدد الفقرات كما تريد، النص لن يبدو مقسما ولا يحوي أخطاء لغوية، مولد النص العربى مفيد لمصممي المواقع على وجه الخصوص، حيث يحتاج العميل فى كثير من الأحيان أن يطلع على صورة حقيقية لتصميم الموقع.
 ومن هنا وجب على المصمم أن يضع نصوصا مؤقتة على التصميم ليظهر للعميل الشكل كاملاً،دور مولد النص العربى أن يوفر على المصمم عناء البحث عن نص بديل لا علاقة له بالموضوع الذى يتحدث عنه التصميم فيظهر بشكل لا يليق.
 هذا النص يمكن أن يتم تركيبه على أي تصميم دون مشكلة فلن يبدو وكأنه نص منسوخ، غير منظم، غير منسق، أو حتى غير مفهوم. لأنه مازال نصاً بديلاً ومؤقتاً.
 ',
            'page_details_en' => '',
        ]);




        Pages::create([
            'page_title_ar' =>'التوصيل',
            'page_title_en' =>'Delivery',
            'page_details_ar' =>' هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو
العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق. إذا كنت تحتاج إلى عدد أكبر من الفقرات يتيح لك مولد النص العربى زيادة عدد الفقرات كما تريد، النص لن يبدو مقسما ولا يحوي أخطاء لغوية، مولد النص العربى مفيد لمصممي المواقع على وجه الخصوص، حيث يحتاج العميل فى كثير من الأحيان أن يطلع
 على صورة حقيقية لتصميم الموقع. ومن هنا وجب على المصمم أن يضع نصوصا مؤقتة على التصميم ليظهر للعميل الشكل كاملاً،دور مولد النص العربى أن يوفر على المصمم عناء
  البحث عن نص بديل لا علاقة له بالموضوع الذى يتحدث عنه التصميم فيظهر بشكل لا يليق. هذا النص يمكن أن يتم تركيبه على أي تصميم دون مشكلة فلن يبدو وكأنه نص منسوخ، غير منظم، غير منسق، أو حتى غير مفهوم.
   لأنه مازال نصاً بديلاً ومؤقتاً. ',
            'page_details_en' => '',
        ]);




        Pages::create([
            'page_title_ar' =>'طرق الدفع',
            'page_title_en' =>'Payment Methods',
            'page_details_ar' =>' هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من
 النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق. إذا كنت تحتاج إلى عدد أكبر من الفقرات يتيح لك مولد النص العربى زيادة عدد الفقرات كما تريد، النص لن يبدو مقسما ولا يحوي أخطاء لغوية، مولد النص العربى مفيد لمصممي المواقع على وجه الخصوص، حيث يحتاج العميل فى كثير من
  الأحيان أن يطلع على صورة حقيقية لتصميم الموقع. ومن هنا وجب على المصمم أن يضع نصوصا مؤقتة على التصميم ليظهر للعميل الشكل كاملاً،دور مولد النص العربى أن يوفر على المصمم عناء البحث عن نص بديل
   لا علاقة له بالموضوع الذى يتحدث عنه التصميم فيظهر بشكل لا يليق. هذا النص يمكن أن يتم تركيبه على أي تصميم دون مشكلة فلن يبدو وكأنه نص منسوخ، غير منظم، غير منسق،
    أو حتى غير مفهوم. لأنه مازال نصاً بديلاً ومؤقتاً. ',
            'page_details_en' => '',
        ]);




        Pages::create([
            'page_title_ar' =>'الأسترجاع والاستبدال',
            'page_title_en' =>'Exchanges',
            'page_details_ar' =>'..هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها
 التطبيق. إذا كنت تحتاج إلى عدد أكبر من الفقرات يتيح لك مولد النص العربى زيادة عدد الفقرات كما تريد، النص لن يبدو مقسما ولا يحوي أخطاء لغوية، مولد النص العربى مفيد لمصممي المواقع
  على وجه الخصوص، حيث يحتاج العميل فى كثير من الأحيان أن يطلع على صورة حقيقية لتصميم الموقع. ومن هنا وجب على المصمم أن يضع نصوصا مؤقتة على التصميم ليظهر للعميل الشكل كاملاً،دور مولد النص العربى أن يوفر على المصمم عناء البحث عن نص بديل لا علاقة له بالموضوع الذى يتحدث عنه التصميم فيظهر بشكل
  لا يليق. هذا النص يمكن أن يتم تركيبه على أي تصميم دون مشكلة فلن
   يبدو وكأنه نص منسوخ، غير منظم، غير منسق، أو حتى غير مفهوم. لأنه مازال نصاً بديلاً ومؤقتاً. ',
            'page_details_en' =>  'Lorem Ipsum is simply dummy text of the printing and
typesetting industry. Lorem Ipsum has been the industry\'s standard dummy
text ever since the 1500s, when an unknown printer took a galley of type and
scrambled it to make a type specimen book. It has survived not only five centuries,
but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised
 in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently
 with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
        ]);




        Pages::create([
            'page_title_ar' =>'الأسئلة المتكررة',
            'page_title_en' =>'FAQ',
            'page_details_ar' =>'هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص
الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق. إذا كنت تحتاج إلى عدد أكبر من الفقرات يتيح لك مولد النص العربى زيادة عدد الفقرات كما تريد، النص لن يبدو مقسما ولا يحوي أخطاء لغوية، مولد النص العربى مفيد لمصممي المواقع على وجه الخصوص، حيث يحتاج العميل فى كثير من
 الأحيان أن يطلع على صورة حقيقية لتصميم الموقعز  ومن هنا وجب على المصمم أن يضع نصوصا مؤقتة على التصميم ليظهر للعميل الشكل كاملاً،دور مولد النص العربى أن يوفر على المصمم عناء البحث عن نص بديل لا
  علاقة له بالموضوع الذى يتحدث عنه التصميم فيظهر بشكل لا يليق. هذا النص يمكن أن يتم تركيبه على أي تصميم دون مشكلة فلن يبدو وكأنه نص منسوخ، غير منظم، غير منسق،
   أو حتى غير مفهوم. لأنه مازال نصاً بديلاً ومؤقتاً',
            'page_details_en' => 'Details',
        ]);




    }
}
